export { default as InstructorDashboard } from "./InstructorDashboard";
export { default as InstructorProfile } from './InstructorProfile';
export { default as ClassroomTrainer } from './ClassroomTrainer'
export { default as TaskTrainer } from './TaskTrainer'
export { default as TaskDetailsTrainer } from '../../../components/instructor/TaskDetailsTrainer'
export { default as CreateNewTask } from '../../../components/instructor/CreateNewTask'
export { default as TaskListTrainer } from '../../../components/instructor/TaskListTrainer'
export { default as TaskDraftList } from '../../../components/instructor/TaskDraftList'
export { default as TaskDetailsTrainerTask } from '../../../components/instructor/TaskDetailsTrainerTask'
export { default as TaskSubmissionLink } from '../../../components/instructor/TaskSubmissionLink'
export { default as CurriculumTrainer } from './CurriculumTrainer'
