export { default as AdminDashboard } from './AdminDashboard';
export { default as AdminProfile } from './AdminProfile';
export { default as CurriculumAdmin } from './CurriculumAdmin'
export { default as CreateNewCurriculumWeek } from './CreateNewCurriculumWeek'
export { default as AdminClassroom } from './AdminClassroom'
export { default as AdminNewLesson } from './NewLesson'
export { default as AboutAdmin } from './AboutAdmin'
export { default as AdminStudentList } from './StudentList'
export { default as AdminTrainerList } from './AdminTrainerList'
export { default as AdminSupport } from './AdminSupport'
export { default as TrainerProfile } from './AminTrainer/TrainerProfile'
export { default as AdminSettings } from './AdminSettings'
